import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Page from './page'
import Reg from './register/page'
// import Auth from '../app/register/Authorization'
import Habits from './habits/page'
import styles from "./layout.module.css";
// import { Router } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "НовыйЯ",  
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className={styles.header}>

          <div className={styles.logo}>
            <img src="/globe.svg" alt="Logo" width={100} height={100} />
            <div className={styles.logoText}>
                <h4>НовыйЯ</h4>
                <p>Свобода от привычек</p>
            </div>
          </div>
          
          <nav className={styles.nav}>
            <Link href="/">Главная</Link>
            <Link href="/about">О нас</Link>
            <Link href="/contact">Контакты</Link>
            <Link href="/register">Регистрация</Link>
            <Link href="/authoriz">Авторизация</Link>
            <Link href="/habits">Привычки</Link>
          </nav>
        </header>

        <main>
          {children}
        </main>

          <footer>
          <p>© 2024 НовыйЯ. Все права защищены.</p>
        </footer>
        </body>
    </html>
  );
}
